### ISSUE TITLE
place_receivers fails when run on exception (but not on supermucNG) with a 684M cells mesh

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/Meshing#50]
(compiled with gcc10)
```
(base) ulrich@exception:/export/dump/ulrich/PUMGEN_folder/Turkey$ gdb -batch -ex run -ex bt --args ~/SeisSol/Meshing/place_receivers/build2/place_receivers -d 5 -m Turkey_extended_13 -r Turkey78_75_dip70_3_stations_proj.txt -o Turkey_extended_13_stations_proj_m5.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Read 484 receivers.
Thu Oct 12 09:00:45, Info:  Found 684983574 cells 
Thu Oct 12 09:00:49, Info:  Found 115877698 vertices 
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x0000155554b3d537 in __GI_abort () at abort.c:79
#2  0x0000155554ecd7ec in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x0000155554ed8966 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x0000155554ed89d1 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x0000155554ed8c65 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000155554ecd2f2 in __cxa_throw_bad_array_new_length () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x000000000040e75d in Mesh::Mesh (this=0x7fffffffbeb0, fileName="Turkey_extended_13") at /home/ulrich/SeisSol/Meshing/place_receivers/src/Reader.cpp:120
#8  0x0000000000405030 in main (argc=9, argv=0x7fffffffc438) at /home/ulrich/SeisSol/Meshing/place_receivers/src/main.cpp:69
```

**Comment by davschneller** [comment]
Fixed by #51
